[build]
  base = "afrixa2"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Header rules
[[headers]]
  # Apply these headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Apply caching headers to static assets
  for = "/static/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
